### ISSUE TITLE
Pipeline Compat

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#106]
Was think a little about interoperability with pipeline and how that would work in user friendly and performant way.

Was think something like this would maybe be nice?

```js
await pipeline(
  src,
  client.pipeline(
    options, 
    async function* req() {
      yield stuff
    }, 
    async function* res(statusCode, headers, body) {
      yield* body
    }
  ),
  dst
)
```

This could be implemented in user land as well using a helper method. But there might be some considerations we could do to make this possible in a performance way. Other than that it might or might not make sense to include such a helper in this library to encourage usage?

First of all adding support for request body to be a generator function. The user could of course just use `Readable.from`, but native support would make things faster.

The next question becomes out the response side. Might or might not be possible to implement the response as a native generator, but it would be difficult to support both streams and generators.

**Comment by mcollina** [comment]
It would be a nice API to add.
