### ISSUE TITLE
Perpetually attempts reconnecting on socket error

### ISSUE THREAD

**Issue by doesdev** [mcollina/undici#11]
## Updated Issue Description

Okay, I see what is happening. So the client reconnects on the emission of `error` from `socket`. It also does so without end. I presume this is by design. 

I'm sure there are plenty of cases where that is needed. However, there are also others where it is problematic.

I've been working on replacing `http-proxy` for a custom reverse proxy I manage. Among the things that proxy does is use proxy errors to signal potential problems with the backend services it manages, as well as do some automated recovery in certain cases.

That being the case having visibility of the inability to reach said services is crucial to the management and recovery of them. It may be that this module is not well suited for that use case, but that is the use case I'm attempting with it atm.

I would propose a solution, but I'm honestly not sure what the best solution would be. I'm going to hack on things locally and see if anything worthwhile comes to mind.

But please let me know your thoughts as I would be happy to do a PR if you have any ideas to manage this without breaking the design philosophy of the module.

### Request Hangs on No Response

Repro is straight forward. With nothing listening on port 3000 run the following and nothing will happen. The `timeout` setting has no effect either.

```js
const { Client } = require('undici')
const client = new Client(`http://localhost:3000`)

client.request({ path: '/', method: 'GET' }, (err, data) => console.log(err || data || 'nothing'))
```

**Comment by doesdev** [comment]
Well, I suppose the above is imprecise. While it does attempt to reconnect that isn't the heart of the issue. Rather, at the time it attempts to reconnect there are 0 callbacks in the queue for the client. While leads to the lack of notification. 

Still digging, but wanted to course correct the above line of thinking about what the core problem is.

**Comment by mcollina** [comment]
If you find the root cause, please send a PR!

**Comment by doesdev** [comment]
Got it, gonna do a quick PR and see if there any design tweaks needed with it. Thanks

**Comment by doesdev** [comment]
Okay, PR #12  is sent. As noted I went for what I thought would have the lowest chance of unintended consequences. That said it does feel slightly hacky. If you have thoughts on a better way to approach it I'd be glad to tackle it. Thanks

**Comment by mcollina** [comment]
I think we should improve the API with a few caveats:

1. a max number of retries for reconnects that will emit an error on the client itself, so we can potentially let the application do something.
2. an offline event, so that the app can do something
3. make the requests error after  a timeout

**Comment by doesdev** [comment]
Those sound like nice enhancements that would definitely address my needs. I can take a stab at those over the next few days and see if I can come up with clean implementations of each.

**Comment by doesdev** [comment]
Unfortunately I haven't been successful tackling the proposed API updates. I did add a `maxRetries` option in [this branch](https://github.com/doesdev/undici/tree/issue-11-api-updates). However, the tricky part is that if a client is initialized against a non-listening URL it will never be placed in `kQueue`, as it will just hang in the reconnect process until `maxRetries` (if set) is hit.

That being the case the callback never gets into the queue and so all affected requests will remain hung even after we emit `maxRetries` and close the client. 

Similarly, in that scenario it will never make it to the timer in order to execute the timeout error on the request. I've tried several methods of working around this, mostly by changing the order of operations around. For instance moving the `if (!this.socket) connect(...)` into the `kQueue` worker function, but this leads to other requests hanging indefinitely.

Similarly I've tried initializing the `Request`, wrapping the callback, and placing it in the queue before the call to connect but that has led to various other issues.

I'm sure there is a way to do this, but unfortunately I've put a good bit of time toward trying and have failed at every turn. I'm not sure if you might want to keep this issue open for any reason, so I'll leave it open for now but feel free to close it.

**Comment by mcollina** [comment]
Thanks for your efforts! I know these problems are hard and those kind of bugs elusive. If you’d still come and take a shot after some time, you are always welcomed!

**Comment by ronag** [comment]
I think we could look at https://www.npmjs.com/package/reconnect-core for some inspiration.

**Comment by ronag** [comment]
I've seen this as well, it goes into a live lock loop of reconnecting.
