### ISSUE TITLE
Improve benchmarks

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#115]
Would be nice to improve our benchmarks and also maybe add some comparison to our README.

**Comment by ronag** [comment]
@szmarczak Is this something you maybe could help out with? You already seem to have some sort of benchmark you run?

**Comment by ronag** [comment]
@mcollina Would you be against adding comparison results to README? I was think it might help with getting some traction.

**Comment by mcollina** [comment]
Go for it!

**Comment by szmarczak** [comment]
> Is this something you maybe could help out with? You already seem to have some sort of benchmark you run?

Sure, I'll be happy to send a PR tomorrow.

**Comment by ronag** [comment]
Done
