### ISSUE TITLE
'drain' can be emitted multiple times

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#125]

**Comment by ronag** [comment]
In theory... I'm unable to make a case which hits it

**Comment by szmarczak** [comment]
Can you reopen this? I'll try to reproduce this tomorrow.

**Comment by ronag** [comment]
I don't think this is possible anymore given.
 https://github.com/mcollina/undici/commit/f6c455bdbbe34e87ebdaebf357f074f0e9a352a9#diff-50cfa59973c04321b5da0c6da0fdf4feR271

**Comment by szmarczak** [comment]
You're right. Feel free to close this now :)
