### ISSUE TITLE
Should `client.destroy()` be able to error?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#127]
I'm not sure whether the it makes sense for `client.destroy()` to error. I haven't really figured out a good use case where it would make sense.

I might want to suggest:

- Remove `err` argument from `destroy(err)`.
- Swallow all errors that occur after the call to `destroy()`. There will be errors of various kind (depending on timings) from destroying the socket, neither of which makes much sense?

**Comment by szmarczak** [comment]
I totally agree with your suggestion. The client itself shouldn't throw, only streams should.
