### ISSUE TITLE
Do we need the `'drain'` event?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#136]
We are not using it for Pool anymore and without it `Client` no longer needs to be a `EventEmitter`?

**Comment by mcollina** [comment]
let’s drop it!

**Comment by ronag** [comment]
I’m not sure it’s worth dropping if we need to keep it as an event emitter anyway. Due to the connect and reconnect events (which btw we should document?).

**Comment by mcollina** [comment]
we should document those.
