### ISSUE TITLE
Limit reading of aborted response body

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#15]
i.e.

```
request(options, (err, { body }) => {
  body.destroy(new Error('aborted'))
})
```

It looks to me like the request keeps processing? Not sure how this can be aborted but maybe it should kill and reconnect the socket?

**Comment by mcollina** [comment]
I think I would let it flow and not error.

**Comment by mcollina** [comment]
Possibly add an option as well

**Comment by ronag** [comment]
> I think I would let it flow and not error.

What if it is a several GB response? I think the safer/generic alternative is to kill the connection and reconnect for queued responses. Though, it's a bit of a problem with pipelining...

**Comment by mcollina** [comment]
That's the problem. An option is needed, I'm happy with whatever default you think is best.
