### ISSUE TITLE
client.pipeline API

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#151]
We recently merged `client.pipeline` in https://github.com/mcollina/undici/pull/147.

Which allows us to do:

```js
stream.pipeline(
  fs.createReadStream('source.raw'),
  client.pipeline({
    path: '/',
    method: 'PUT',
  }, ({ statusCode }) => {
    if (statusCode !== 201) {
      throw new Error('invalid response')
    }
  }),
  fs.createReadStream('response.raw'),
  (err) => {
    if (err) {
      console.error('failed')
    } else {
      console.log('succeeded')
    }
  }
)
```

However, I was discussing with some collegues the API in regards to whether one would like to modify the stream based on headers. Where the suggestion was to change it to:

```js
stream.pipeline(
  fs.createReadStream('source.raw'),
  client.pipeline({
    path: '/',
    method: 'PUT',
  }, ({ statusCode, headers, body }) => {
    if (statusCode !== 201) {
      throw new Error('invalid response')
    }
    // NOTE: This is different. Receives a `body` and returns a `Readable`.
    // Perform body transformation based on statusCode & headers.
    return isZipped(headers) ? pipeline(body, unzip(), () => {}) : body
  }),
  fs.createReadStream('response.raw'),
  (err) => {
    if (err) {
      console.error('failed')
    } else {
      console.log('succeeded')
    }
  }
)
```

i.e. the `handler` receives a `body` and must return a stream (which usually would simply be `body`). This makes it more similar with `client.stream`. If nothing is returned then `client.pipeline` will automatically and immediately end the returned `Duplex`.

Makes sense?

**Comment by ronag** [comment]
@mcollina @szmarczak

**Comment by mcollina** [comment]
go for it

**Comment by szmarczak** [comment]
Isn't it better to decompress the response automatically? And have an option to disable it?

**Comment by ronag** [comment]
> Isn't it better to decompress the response automatically? And have an option to disable it?

That kind of goes into user land and modules (e.g. got). I think this library should do as little as possible.
