### ISSUE TITLE
throw or callback?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#154]
We are a little inconsistent in regards to throwing and using the callback.

For argument errors directly in `request`, `stream` and `pipeline` we `throw`. While errors from `Request` constructor we propagate through the `callback`.

I think we should probably pick one. Should we go with always propagate through callback?

**Comment by delvedor** [comment]
+1 for callbacks!
As a library maintainer I very much prefer to use callbacks instead of try catches :)
