### ISSUE TITLE
Pipelining only for GET/HEAD

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#16]
Pipelining should only be performed for GET/HEAD requests. If any other requests comes into the queue I guess it should wait for drain and reconnect, or error?

**Comment by mcollina** [comment]
Good spot, yes. This is not implemented.

**Comment by ronag** [comment]
Actually we could consider whether to pipeline PUT/DELETE as well as long as they are idempotent. Could we maybe add an option to request where the user can specify if a requests is idempotent or not, and we auto assume GET/HEAD are idempotent.

**Comment by ronag** [comment]
This would be easier to implement with an async/await loop... e.g.

```js
let pending = []
async function enqueue(req) {
  queue.push(req)
  if (queue.length > 1) {
    return
  }
  while (queue.length) {
    req = queue.shift()
    if (!req.idempotent) {
      await Promise.all(pending)
      pending = []
    }
    if (pending.length < concurrency) {
      pending.push(dispatchRequest(req))
    } else {
      await pending[0]
      pending.shift()
    }
  }
}
```

Instead of the `Q` queue. @mcollina would you be opposed to such a direction?

**Comment by mcollina** [comment]
That’s going to lose throughput :(. fastq is extremely low overhead.

**Comment by ronag** [comment]
> That’s going to lose throughput :(. fastq is extremely low overhead.

Simplicity vs performance 😄. It's a bit trickier but if you prefer fastq I'll try and see if I can fix it with that approach...

**Comment by mcollina** [comment]
The purpose of this module is to be fast ;)

**Comment by ronag** [comment]
ah yes, fastify, not simplify ;), I'll try to keep that in mind
