### ISSUE TITLE
Experimental support in the Elasticsearch Node.js client

### ISSUE THREAD

**Issue by delvedor** [mcollina/undici#160]
Hello folks!
As you may know, Elasticsearch uses HTTP as communication protocol, and I've been looking at this library for a while :)
I would love to add experimental support in the client for this library, so users can start using it and reporting how it works.

Using it would be something like:
```js
const { Client, UndiciConnection } = require('@elastic/elasticsearch')
const client = new Client({
  node: 'http//localhost:9200',
  Connection: UndiciConnection
})
```

When are you expecting to have an "almost stable" release?
Is there something I can do for helping out?

Thanks!

**Comment by ronag** [comment]
@delvedor Awesome!

> When are you expecting to have an "almost stable" release?

I believe most of what's left is increasing test coverage. My intention is to propose a release by the beginning of next week.

> Is there something I can do for helping out?

If you can review the API and make sure it makes sense and see if you can see any missing edge cases in terms of functionality or error handling that would be great.

**Comment by ronag** [comment]
I know elasticsearch uses `GET` requests with a body. Are those idempotent?

**Comment by delvedor** [comment]
> I believe most of what's left is increasing test coverage. My intention is to propose a release by the beginning of next week.

Awesome!

> If you can review the API and make sure it makes sense and see if you can see any missing edge cases in terms of functionality or error handling that would be great.

👍 

> Out of curiosity. We have 3 different API's request, pipeline and stream. Which one do you intend to use?

Very likely the `request` API, the internals of the Elasticsearch client are built to be interchangeable, but there is a contract that must be respected.
Any `Connection` class (which is a wrapper of an HTTP client library), must return a ReadableStream from which the coordinator of the request will consume the response. It also needs status code and headers. Also, the `idempotent` will always be false, as the failover mechanism is handled by the request coordinator.

> I know elasticsearch uses GET requests with a body. Are those idempotent? Would you need this #112? Or are the request bodies normal strings (i.e. not streams).

Elasticsearch does support GET requests with a body, but it does support POST/PUT as well. The Node.js client never uses GET when there is a body, so this should not be an issue :)
The body can be either a string, buffer or stream, in case of a stream the client will never retry the request.

**Comment by ronag** [comment]
> Also, the idempotent will always be false, as the failover mechanism is handled by the request coordinator.

If you set `idempotent` to always `false` then undici won't pipeline the requests. Which is fine unless you expect requests to be pipelined.

**Comment by ronag** [comment]
Also if you have any notes on the documentation please add them here https://github.com/mcollina/undici/issues/161 and if you have suggestions for improvement feel free to open a PR.

**Comment by ronag** [comment]
If you intend to use pipelining it would be intersting to get your take on https://github.com/mcollina/undici/issues/73.

**Comment by delvedor** [comment]
I'm playing with undici inside the client and I can already give some early feedback:

1. In the Node.js's core `http.request` method you have different events you can listen, and based on the event, you can return a different error (timeout, abort, error). With undici you will receive every error in the same callback, it would be great to codify these errors in their own classes (such as TimeoutError, AbortError..) so a library consumer can handle those errors easily.

2. Aborting a request should be easier than calling destroy on the request/response body, it would be nice to have a convenience method to do this.

If you like, I can work on the points above :)
Thank you for the links to the other issues, I'll answer there as soon as I have something for you!

**Comment by ronag** [comment]
> 1.

PR is welcome!

> 2.

**Comment by delvedor** [comment]
> Do you have any suggestion on how the API would look? Some kind of abort controller like in fetch?

I was thinking about something very easy, for example:
```js
const request = pool.request({ params }, (err, data) => {
  console.log(err) // RequestAbortedError
})

request.abort()
```

With promises it should be a thenable.
```js
const request = pool.request({ params })

request
	.then(console.log)
	.catch(console.log) // RequestAbortedError

request.abort()
```

**Comment by ronag** [comment]
> I was thinking about something very easy, for example:

That breaks the API thought. Currently `request` returns a `Boolean`.

> With promises it should be a thenable.

So we monkey patch a Promise? Not sure I like it.

Could you create a separate issue for this and we can discuss it there? I feel this might require a bit of back and forth.

**Comment by delvedor** [comment]
> So we monkey patch a Promise? Not sure I like it.

I would not define it monkey patching, I was thinking something like the following:
https://github.com/elastic/elasticsearch-js/blob/d1ad7bd22bcaac412daf4ba330ddbb544e651f8c/lib/Helpers.js#L179-L193

> Could you create a separate issue for this and we can discuss it there? I feel this might require a bit of back and forth.

Sure!

**Comment by ronag** [comment]
@delvedor anything else you need in terms of functionality? If we are feature complete, will start more in depth review during next week and hopefully we can do a release after that.

**Comment by delvedor** [comment]
I think so, but I'll do some test asap to be sure :)

**Comment by ronag** [comment]
@szmarczak ping as well. I expect we should be able to make a 1.0 release in the next few days unless there is any further feedback or requests.

**Comment by delvedor** [comment]
@ronag sorry for the delay, unfortunately, I need to finish something else first.  
My first test looks promising, and I think we are good to go for an initial release.
If something comes up in the future I'll update this issue or directly send a pr :)

**Comment by ronag** [comment]
Published 1.0.0 🎉

**Comment by ronag** [comment]
@delvedor any updates here? Can we close this?

**Comment by delvedor** [comment]
For now, yes! I'll let you know how it goes!
