### ISSUE TITLE
Expose a simple API to abort requests

### ISSUE THREAD

**Issue by delvedor** [mcollina/undici#164]
With the current API it is not straightforward to abort a request, it would be great to expose a simple method to abort a request.

I was thinking about something very easy, for example:
```js
const request = pool.request({ params }, (err, data) => {
  console.log(err) // RequestAbortedError
})

request.abort()
```

With promises it should be a thenable.
```js
const request = pool.request({ params })

request
	.then(console.log)
	.catch(console.log) // RequestAbortedError

request.abort()
```

For supporting this signature, we should transform the returned value in a thenable.
Otherwise, we could create something similar to the [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort).

What do you think?

Related: https://github.com/mcollina/undici/issues/160

**Comment by ronag** [comment]
@szmarczak @mcollina

**Comment by mcollina** [comment]
+1!

**Comment by ronag** [comment]
Then we change so that request no longer returns a Boolean.

@mcollina does using a thenable instead of a promise in anyway affect async hooks, async await etc...?

**Comment by mcollina** [comment]
I think using abortcontroller is better.

thenables can break the async context badly :(

**Comment by ronag** [comment]
I think abortcontroller was discussed in node core somewhere. Will see if I can find that issue.

**Comment by mcollina** [comment]
See how it is implemented in https://github.com/jasnell/piscina#cancelable-tasks. I think it's a great way to add it.

**Comment by delvedor** [comment]
I'm going through the code for looking at how to implement the abort controller.
Supporting it is quite easy, in the end it will be something like:
```js
if (opts.signal != null) {
  opts.signal.on('abort', () => {
    callback(new RequestAbortedError(), null)
  })
}
```
I don't know well enough the internals to know where and what to close/destroy to clean the used resources. @ronag can you point me in the right direction? Or if you want to take a stab, go for it!
I think we should first solve this issue, and then we can work on https://github.com/mcollina/undici/issues/165.

**Comment by ronag** [comment]
> I think we should first solve this issue, and then we can work on #165.

Yes, I agree.

> Or if you want to take a stab, go for it!

I'll sort it out. If you'd like to build some additional test cases for it afterwards that would be great.

**Comment by szmarczak** [comment]
In Got we just expose a `.cancel()` function. It destroys the pending request and makes the promise reject.

**Comment by ronag** [comment]
> In Got we just expose a .cancel() function. It destroys the pending request and makes the promise reject.

What do you expose it on? Do you mean to return a thenable object, i.e. not a `Promise`?

**Comment by szmarczak** [comment]
```js
const promise = got('https://example.com'); // This is a promise
promise.cancel(); // The promise will throw an error
```

**Comment by ronag** [comment]
@szmarczak Unfortunately that won't work as [thenables break async context](https://github.com/mcollina/undici/issues/164#issuecomment-630779518).

**Comment by mcollina** [comment]
@szmarczak that can work if you add a `cancel` function to the promise object.

**Comment by ronag** [comment]
> that can work if you add a cancel function to the promise object.

Are we fine with modifying the `Promise` object?

**Comment by mcollina** [comment]
I would try to use the abortcontroller approach instead which is going to be more compatible with the rest of the ecosystem.
