### ISSUE TITLE
`close` semantics

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#175]
Extracting this out from the timeout PR.

It's for me a little unclear what exactly the expected semantics of close is and whether it's worth the complexity.

If we want to keep it I would like to suggest that the expected semantics of close would be:

```js
async function close(client) {
  await Promise.all(client.allRequests.map(x => x.promise))
}
```

i.e. it waits for completion for all queued and active requests and if any of those fail it will fail.

Alternatively it could be corresponding to `Promise.allSettled`?

I'm a little unsure. I would prefer that we either figure out the semantics properly, or simply remove `close` until we have done so. I don't see it as a must have feature as graceful shutdown can also be implement in user space.

**Comment by mcollina** [comment]
While graceful shutdown can be implemented in user space, it’s hard for most devs. It’s better if we keep it in here.

I agree with the semantics of Promise.all.

**Comment by ronag** [comment]
> I agree with the semantics of Promise.all.

Ok, I'll try to make that happen and label this as a bug until then.
