### ISSUE TITLE
HTTP Trailers

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#179]

**Comment by ronag** [comment]
@szmarczak is this a requirement for got?

**Comment by szmarczak** [comment]
I'd rather say no. I don't know if there are any valid use cases but even if it'll become an issue then we can implement trailers later, right?

**Comment by ronag** [comment]
>  but even if it'll become an issue then we can implement trailers later, right?

Just checking whether this is something we need to fix before doing a release.

**Comment by ronag** [comment]
@delvedor I assume this is not a problem for elasticsearch?

**Comment by ronag** [comment]
On second thought. It might be worth at least considering how the API for this would look like. In order to avoid future breaking changes.

**Comment by delvedor** [comment]
@ronag it should not be an issue.

**Comment by ronag** [comment]
Giving this more thought I believe this can be solved in an elegant fashion by providing a `trailers` promise beside the `headers` object.

**Comment by trygve-lie** [comment]
Related topic; how would HTTP [103 Early Hints](https://evertpot.com/http/103-early-hints) play out? It would be very nice to have a way to get the early hints data in a way before the header and body.

I have a real use case for 103.

**Comment by ronag** [comment]
I'm unsure if https://www.npmjs.com/package/http-parser-js supports this.

**Comment by ronag** [comment]
The "engine" can now do early hints and trailers. However we don't have a public API for it yet.

**Comment by ronag** [comment]
I'm not sure what is a good API for informational headers and trailers. Any ideas? @mcollina @szmarczak @delvedor.

I'm not too fond of having `onInfo` and `onTrailer` options but it's the best I can think of at the moment.

**Comment by mcollina** [comment]
Go for `onInfo()` and `onTraliers` as options. I like it.
