### ISSUE TITLE
Provide error as reconnect argument?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#184]
Should we forward the the socket error to the `'reconnect'` event so that an observer can get some kind of hint to why the client is reconnected.

**Comment by mcollina** [comment]
I think it would be a good idea

**Comment by mcollina** [comment]
Also a disconnect event could work

**Comment by ronag** [comment]
Should we rename reconnect to disconnect?

**Comment by mcollina** [comment]
let's go with reconnect and see

**Comment by ronag** [comment]
fixed
