### ISSUE TITLE
Response headers

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#190]
Should we change the type of response headers to better match https://developer.mozilla.org/en-US/docs/Web/API/Headers?

i.e. an object with the following methods:

- `entries()`
- `get()`
- `has()`
- `keys()`
- `values()`

i.e. make it a `Map` instead of an object.

I'm mostly bringing this up since it was mentioned on the webserverframework meeting that the `Headers` API seemed promising and if we do it like this we would be forward compatible with this.

Should also probably add so that the request header can also implement this trait.

**Comment by ronag** [comment]
@mcollina

**Comment by mcollina** [comment]
That’s terribly slow :(. @delvedor did some experiments already.

**Comment by ronag** [comment]
> That’s terribly slow :(. @delvedor did some experiments already.

That makes me sad :(

**Comment by ronag** [comment]
Any ideas as to why and what V8 versions did @delvedor try?

**Comment by delvedor** [comment]
I did some experiments, but I didn't benchmark them actually.
While I like this idea, I fear that the main issue is that people are used to have headers inside a plain object. If we start returning headers in whatwg-headers flavor, people will start converting them in plain objects, and they will have performance issues.

**Comment by ronag** [comment]
@mcollina any further thoughts or close?

**Comment by mcollina** [comment]
I'll close for now.
