### ISSUE TITLE
HTTP 103 Early Hints

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#196]
https://evertpot.com/http/103-early-hints

Request from: https://github.com/mcollina/undici/issues/179

> Related topic; how would HTTP 103 Early Hints play out? It would be very nice to have a way to get the early hints data in a way before the header and body.
> 
> I have a real use case for 103.

@trygve-lie

**Comment by ronag** [comment]
I'm unsure if https://www.npmjs.com/package/http-parser-js supports this.

**Comment by ronag** [comment]
Does Node core supports this? @mcollina do you know?

**Comment by mcollina** [comment]
I _think_ Node.js core support this.

**Comment by trygve-lie** [comment]
Yeah. Node.js core supports it: https://github.com/nodejs/node/pull/16644

**Comment by ronag** [comment]
@mcollina @szmarczak @delvedor I don't really see a future way forward given the current API to support 1xx informational responses...

Maybe in the `request.stream` API we could invoke the `handler` multiple times and when the `body` is nully then it should be interpreted as informational response?

**Comment by ronag** [comment]
If we don't support 101 should we throw on method `CONNECT`?

**Comment by mcollina** [comment]
Throw on 101.

I'm happy with the rest.

**Comment by ronag** [comment]
> I'm happy with the rest.

I assume you mean that you are happy with the status quo?

**Comment by mcollina** [comment]
I'm happy to cut a release with no 103 early hints.

@trygve-lie what's your use case?
