### ISSUE TITLE
Client.close w callback or event?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#20]
Currently I don't think it's possible to determine when a client has completed all queued requests after calling `Client.close()` should we add a callback parameter or alternatively emit a `'close'` event?

**Comment by mcollina** [comment]
I would add a callback

**Comment by ronag** [comment]
Should close wait for queued requests as well? I'm a little unsure which behavior is most intuitive. If I wanted to kill requests I would call `destroy` while I would expect `close` to gracefully finish everything that has been requested so far.

**Comment by mcollina** [comment]
I would say it should have both close() and destroy() with the semantic you identified.
