### ISSUE TITLE
Optimize `request.pipeline` writing

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#208]
It should be possible to have the returned `Duplex` write directly to the socket. Instead of providing a `Readable` as request body we can provide a function, i.e. the reverse of what we do on the response side in `request.enqueue`.

This would allow us to entirely bypass the intermediate `PassThrough` or `Readable` between the `Duplex` and the socket.

**Comment by ronag** [comment]
Might also make use of `WritableBase` which is being worked on [here](https://github.com/nodejs/node/pull/33515). Could extract that out into this library to make use of it.

**Comment by mcollina** [comment]
go for it

**Comment by szmarczak** [comment]
I ran the benchmarks on `master` again. I got:

```
http - keepalive - pipe x 9,623 ops/sec ±3.24% (76 runs sampled)
undici - request - pipe x 16,881 ops/sec ±0.45% (86 runs sampled)
undici - pipeline - pipe x 11,107 ops/sec ±0.81% (87 runs sampled)
undici - stream - pipe x 17,350 ops/sec ±0.61% (86 runs sampled)
```

Indeed it's still [faster than the native `http2` module](https://github.com/szmarczak/http2-wrapper#benchmarks) :tada:

*Also I fixed the `h2o.conf` in `http2-wrapper` so when you clone the repo you can easily start the server just by running
`h2o -c h2o.conf` (no need to clone the examples in the h2o repository).*

**Comment by ronag** [comment]
Let's stick to normal streams and not go too crazy here. pipeline has reasonable perf now.
