### ISSUE TITLE
https considerations

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#209]
I noticed the Node `https.Agent` has a some extra considerations for `TLS` connections. Are we missing something? Seems to be some form of session cache.

https://github.com/nodejs/node/blob/master/lib/https.js#L147

**Comment by ronag** [comment]
@mcollina

**Comment by mcollina** [comment]
Yes, we are missing features.

**Comment by ronag** [comment]
Probably a nice to have, https://github.com/mcollina/undici/issues/210

Anything else?
