### ISSUE TITLE
Invalid char in header strategy

### ISSUE THREAD

**Issue by dnlup** [mcollina/undici#227]
Hi :wave: !

I have a use case in which I have to check for invalid characters in headers (like control characters). Node already [does this](https://github.com/nodejs/node/blob/master/lib/_http_outgoing.js#L529) by default, on both server and client. I was wondering what strategy you would suggest for undici. Should this be implemented in userland space? Should undici do it?

**Comment by ronag** [comment]
I think tjats doneringar for userland.

**Comment by dnlup** [comment]
Makes sense, thank you.
