### ISSUE TITLE
Add property indicating whether further requests will be pipelined or not

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#231]
`full` doesn't give a full picture, i.e. if there is a non idempotent and/or streaming request in the queue no further pipelining can be performed following it and until it has completed, hence we should indicate that dispatching further requests has no advantage.

Change the semantics of `full` or add a different property?

**Comment by mcollina** [comment]
I think the name `full` is misleading. Let's use a better name with cleaner semantics.

**Comment by ronag** [comment]
@mcollina Should we remove `full`? Seems a bit unnecessary as you can just do `size > pipelining` yourself.

**Comment by mcollina** [comment]
go for it!
