### ISSUE TITLE
How to make a GitHub release?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#239]
I'm a little unfamiliar with the flow here.

Usually I just run:

```bash
npm version 1.x.x
npm publish
git push
```

Sometimes I open a PR after npm version and before npm publish, which includes the package.json update  CHANGELOG.md changes which other collaborators then can also approve. Though a GitHub release with notes seems much nicer than a CHANGELOG.md.

But how would I go about doing a GitHub release with a changelog at the same time? I've kind of figured out how to do a GitHub release OR a npm release. But how do I go about doing both for a specific release?

Haven't manage to bring much clarity in this through googling. Anyone with any advice?

**Comment by ronag** [comment]
@szmarczak @mcollina

**Comment by szmarczak** [comment]
Unfortunately I don't have any experience with GitHub Releases :|

**Comment by szmarczak** [comment]
I don't have much experience with GitHub Releases. All I've done is by hand. Perhaps you need a bot? Dunno.

**Comment by ronag** [comment]
I now see you can select a specific commit to create a release from. I guess I should just do the npm procedure as usual and then create a release from that commit.
