### ISSUE TITLE
Content-Length header handling

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#253]
How should we handle the `content-length` header if provided by the user?

Currently, it's overriden if the "proper" value can be determined based on the `body`. The user provided value is basically only used when the `body` is a stream.

My primary question is what to do if the user provided content-length does not match the computed one? 

1. Ignore silently? (current)
2. Error? 
3. Always use the user provided one?
4. Some combination of 2 and 3?

As it is now it is not possible to e.g. provide a `content-length` header for a request without `body`, such as a `HEAD` request, with a  special case for `PUT`, `POST` and `PATCH` where it is set to `0` if there is no `body`. Though, I don't *think* this is a problem.

Second question. What to do when using the user provided `content-length` and it doesn't match the actual `body` (especially when using streams) which is either longer or shorter?

**Comment by ronag** [comment]
@szmarczak @delvedor

**Comment by mcollina** [comment]
Let's be strict and error.
