### ISSUE TITLE
Expected disconnect errors

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#255]
Currently we provide an error with every disconnect which gives the user a hint in regards to why the client disconnected. Usually this is because of an error, however there are cases where we disconnect on purpose, in which case the user currently gets a generic "socket closed" error.

There are a few cases where we intentionally close the socket:

- Request was aborted and the response has a large payload.
- The current request's SNI is different than the current connection's.
- We intentionally reset the connection to protect state from potential undefined server behaviors.

How should we handle these? They are not errors per se but I guess the only way to propagate them is as errors. Should we create a new error type for this e.g. `InformationalError`? Should we have a second string argument to `'disconnect'` which is `reason` if `err` is null?

**Comment by ronag** [comment]
@szmarczak @delvedor

**Comment by mcollina** [comment]
> How should we handle these? They are not errors per se but I guess the only way to propagate them is as errors

I would treat them as errors. I'm also ok in adding a `reason` to the `'disconnect'` event.

**Comment by ronag** [comment]
> I would treat them as errors

So a `InformationalError` error type then?

**Comment by mcollina** [comment]
yes!

**Comment by ronag** [comment]
Fixed in https://github.com/mcollina/undici/commit/818320771abb61d9f180e2765100b3e4f8412ad9

**Comment by delvedor** [comment]
@ronag I would check for the error code instead of relying on `instanceof` as it's an order of magnitude faster.

**Comment by ronag** [comment]
@delvedor also fixed :)
