### ISSUE TITLE
Reset connection after HEAD?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#258]
Continuing from https://github.com/nodejs/node/issues/34350.

Some servers send a body with HEAD requests which is kind of un-parsable. There is however one way to be resilient against it. Always reset the connection after receiving the message headers for a HEAD request.

This would make things significantly slower though but much more resilient. How important are HEAD requests?

Should we just ignore this unfortunate case and hope that the target server behaves properly?

Opt-in/Opt-out option?

**Comment by ronag** [comment]
@szmarczak @delvedor

**Comment by szmarczak** [comment]
Can't we just throw on `transfer-encoding: chunked`?

**Comment by szmarczak** [comment]
If there's any data that we don't expect, we can also reset the connection at that point.

**Comment by ronag** [comment]
> Can't we just throw on transfer-encoding: chunked?

That's a valid header for a HEAD response?

> If there's any data that we don't expect, we can also reset the connection at that point.

Hard to determine. What if the extra data (i.e. HEAD body) contains data that looks like a proper request?

**Comment by szmarczak** [comment]
> That's a valid header for a HEAD response?

Ah, you're right.

> What if the extra data (i.e. HEAD body) contains data that looks like a proper response?

Then resetting the connection would make sense, but indeed, it would be a significant performance drop. But there are lots of edge cases like that so I wouldn't go for this.

IMO, if it looks like a proper response, it should be parsed, and if the `path` doesn't match with the pipelined request (or there isn't any) then throw.

**Comment by szmarczak** [comment]
> But there are lots of edge cases like that so I wouldn't go for this.

E.g. GET receives `content-length: 0` but there is actually a body...

**Comment by ronag** [comment]
Yea, I guess it's not really solvable.

**Comment by ronag** [comment]
> E.g. GET receives content-length: 0 but there is actually a body...

We could reset connection after content-length: 0 as well 😄

**Comment by ronag** [comment]
So it turns out that Node actually does reset connection after HEAD. See, https://github.com/nodejs/node/issues/12396.

I think it might make sense for us to do so as well.

Thoughts? @mcollina @szmarczak

**Comment by mcollina** [comment]
+1
