### ISSUE TITLE
Server response before request body sent

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#259]
It is possible for the server to send a complete response *before* the client has sent the entire request payload. Currently when this happens we reset the connection.

What is the correct client behavior in this case?

1. Keep writing the request payload until end?
2. Stop writing the request payload and continue with the next request? (probably confuses server parser)
3. Reset the connection.

We could do a combination of 1. and 3. where it keeps writing until "maxAbortedPayload", similar to what we do with responses for aborted requests. However, this seems like an edge case so I'm not sure it's worth the complexity.

I'm fine with the current behavior with 1. Just wanted to check for some second opinions.

**Comment by ronag** [comment]
@szmarczak @delvedor

**Comment by ronag** [comment]
I'm actually a bit unsure what the spec says on this topic. Is a server allowed to respond before consuming the entire payload?

**Comment by szmarczak** [comment]
I couldn't find anything that would prohibit sending response before receiving full payload.

The server can send us trailers, no? So maybe 1 or 3 is the way to go...
