### ISSUE TITLE
SSL over unix socket fails

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#267]
A broken test failed to catch this. Is it possible to fix?

```js
 test: test/unix.js https get with tls opts
  origin:
    library: SSL routines
    function: ssl3_get_record
    reason: wrong version number
    code: ERR_SSL_WRONG_VERSION_NUMBER
  found:
    !error
    name: Error
    message: >
      4603977152:error:1408F10B:SSL routines:ssl3_get_record:wrong version
      number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
    stack: "Error: "
    library: SSL routines
    function: ssl3_get_record
    reason: wrong version number
    code: ERR_SSL_WRONG_VERSION_NUMBER
  stack: |
    test/unix.js:71:11
```

**Comment by ronag** [comment]
@yoshuawuyts

**Comment by ronag** [comment]
https://github.com/mcollina/undici/blob/master/test/unix.js#L47-L84

**Comment by szmarczak** [comment]
The error basically means that the socket is not a TLS one. Most likely it's plain, unsecured TCP one.

**Comment by szmarczak** [comment]
I'll look at this tomorrow morning.

**Comment by ronag** [comment]
@szmarczak any update?

**Comment by szmarczak** [comment]
https://github.com/mcollina/undici/blob/6b931cd367b231eeefedb2c7208938f58cb7e5fb/test/unix.js#L6

You sure you want to assign `require('http')` to `https`? Hehe. Just fix this and it works :P

**Comment by ronag** [comment]
Thansk!
