### ISSUE TITLE
HTTP keep-alive header support

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#272]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive

**Comment by ronag** [comment]
Not sure how useful this is in practice.

**Comment by delvedor** [comment]
Isn't this library already keeping sockets alive?

**Comment by ronag** [comment]
Yes, this header is fo providing hints

**Comment by ronag** [comment]
@szmarczak Any ideas of when this is useful? Or someone that might know?

The only case I can think of is https://github.com/mcollina/undici/pull/273

**Comment by ronag** [comment]
I guess the server could indicate max pipelining maybe?

**Comment by ronag** [comment]
https://github.com/mcollina/undici/pull/273#issuecomment-666243480

> I have no idea. I might be interested in implementing it for Node core.

From looking at nginx docs, it seems an header that is send from the server to the client.

From http://nginx.org/en/docs/http/ngx_http_core_module.html

> The first parameter sets a timeout during which a keep-alive client connection will stay open on the server side. The zero value disables keep-alive client connections. The optional second parameter sets a value in the “Keep-Alive: timeout=time” response header field. Two parameters may differ.

> The “Keep-Alive: timeout=time” header field is recognized by Mozilla and Konqueror. MSIE closes keep-alive connections by itself in about 60 seconds.

_Originally posted by @mcollina in https://github.com/mcollina/undici/pull/273#issuecomment-666243480_

**Comment by szmarczak** [comment]
> Not sure how useful this is in practice.

Me neither...

**Comment by ronag** [comment]
I think we fixed the relevant parts of this in https://github.com/mcollina/undici/pull/275

**Comment by ronag** [comment]
nginx has a weird option:

> keepalive_requests – The number of requests a client can make over a single keepalive connection. The default is 100, but a much higher value can be especially useful for testing with a load‑generation tool, which generally sends a large number of requests from a single client.

See, https://www.nginx.com/blog/tuning-nginx/.

I suppose this is the "max" hint. But I don't see why one would ever want this?

**Comment by BlueClouDragon** [comment]
how to set  keep-alive connection in headers?
