### ISSUE TITLE
`socketPath` not being passed into `Client` from `Pool`

### ISSUE THREAD

**Issue by timsuchanek** [mcollina/undici#281]
As in the [unix domain sockets test](https://github.com/mcollina/undici/blob/25ce5c740cc4845ccaf392af72ee2b79d429a77b/test/unix.js#L23), the `Client` gets passed in the `socketPath` like so:
```ts
const client = new Client({
  hostname: 'localhost',
  protocol: 'http:'
}, {
  socketPath: '/var/tmp/test3.sock'
})
```

However, in the `Pool` implementation, that arg is not passed in:
https://github.com/mcollina/undici/blob/master/lib/pool.js#L27

It looks like this would be a small patch, making sure, that the `socketPath` argument is being passed from `Pool` down to `Client`.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by timsuchanek** [comment]
Yes, on it :)

**Comment by timsuchanek** [comment]
Done :)
