### ISSUE TITLE
global idle connection limit?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#292]
Currently if you have a high idle timeout + create a new client instance of every request + don't call destroy on the instances. You can start leaking lot's of connections waiting for their idle timeout.

It is kind of a user error but should we help out here with e.g. a global per host limit? If the limit is reached we either warn or start closing connections.

I foresee this could become a common user mistake.

**Comment by ronag** [comment]
@mcollina @szmarczak

**Comment by mcollina** [comment]
That's why I originally added the Pool object.

**Comment by ronag** [comment]
> That's why I originally added the Pool object.

No sure if that's enough though?

**Comment by ronag** [comment]
I was thinking of a warning similar to `addListener` in Node core.

**Comment by mcollina** [comment]
I'm afraid this will backfire on us somehow
