### ISSUE TITLE
Low Level API

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#293]
The recent info/trailers API discussion has made me consider whether we should provide a low level unopinionated API which library & framework authors can use to experiment and develop appropriate API's.

I was thinking of something like the following, which basically exposes the internal API we use to implement the existing public API's.

```js
client.dispatch(options, {
  onUpgrade (statusCode, headers, socket) {
  },
  onConnect (pause, resume) {
  },
  onInfo (statusCode, headers) {
  },
  onHeaders (statusCode, headers) {
  },
  onData (chunk) {
  },
  onComplete (trailers) {
  },
  onError (err) {
  }
})
```

I would then consider our existing public API implementations as simply reference implementations.

EDIT: Updated

**Comment by ronag** [comment]
@mcollina @szmarczak @delvedor

**Comment by mcollina** [comment]
How is backpressure managed for the body?

**Comment by ronag** [comment]
> How is backpressure managed for the body?

That's the only thing I'm unsure of right now. One way would be:

- if returns `falsy`, `callback/resume` must be invoked to resume.

Any alternative ideas?

**Comment by ronag** [comment]
Alternative:

```js
onBody (chunk, callback) {
  if (writable.write(chunk)) {
    callback()
  } else {
    writable.once('drain', callback)
  }
}
```

**Comment by ronag** [comment]
Alternative:

```
onBody (chunk) {
  if (writable.write(chunk)) {
    return true
  } else {
    writable.once('drain', this.resume)
  }
}

```

**Comment by ronag** [comment]
Alternative:

Again close to what we have today.

```
client.dispatch(..., {
  onInit (resume) {
    writable.on('drain', resume)
  },
  onBody (chunk) {
    return writable.write(chunk)
  }
})

**Comment by ronag** [comment]
Alternative:

Just keep it like we have it:

```js
client.dispatch(..., {
  onHeaders (statusCode, headers, resume) {
    writable.on('drain', resume)
  },
  onBody (chunk) {
    return writable.write(chunk)
  }
})
```

**Comment by ronag** [comment]
Alternative:

Again close to what we have today.

```js
client.dispatch(..., {
  onBody (chunk) {
    return writable.write(chunk) ? null : (resume) => writable.on('drain', resume)
  }
})

**Comment by ronag** [comment]
Updated proposal in first post.

Example with backpressure:

```js
const dst = fs.createWriteStream(...)
client.dispatch(options, {
  onConnect (pause, resume) {
    this.pause = pause
    dst.on('drain', resume)
  },
  onData (chunk) {
    if (!dst.write(chunk)) {
      this.pause()
    }
  },
  onComplete (trailers) {
    dst.end()
  },
  onError (err) {
    dst.destroy(err)
  }
})
```

@mcollina: wdyt?

**Comment by mcollina** [comment]
I like it. For biggish payloads this is going to be faster than our current options.

**Comment by delvedor** [comment]
I really like this proposal :)

**Comment by ronag** [comment]
implemented
