### ISSUE TITLE
Future performance improvements

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#304]
Currently (as far as I can tell) the largest bottleneck is in the tls and net socket implementations. Doing something like https://www.npmjs.com/package/turbo-net or making js bindings for https://github.com/uNetworking/uSockets might be the next significant step up in terms of performance. Thought that would break the compatibility with the node http parser at least in terms of the consume/unconsume API's.

**Comment by mcollina** [comment]
I'm not in favor of this approach as it would introduce a binary addon, which would limit adoption.
