### ISSUE TITLE
Move to nodejs org?

### ISSUE THREAD

**Issue by mcollina** [mcollina/undici#312]
The original purpose of this module was to experiment in building the next-gen http/1.1 client for Node.js.
I think this library is now mature enough, mainly thanks to @ronag :).

Should we move this to the nodejs org and give it a little bit of a blessing?

**Comment by ronag** [comment]
Sounds good to me!

**Comment by delvedor** [comment]
LGTM :)

**Comment by mcollina** [comment]
Let's ask to the tsc then.
