### ISSUE TITLE
Doesn't work within jest

### ISSUE THREAD

**Issue by timsuchanek** [mcollina/undici#318]
When running an undici client in jest, jest is doing some kind of override magic in the background, that makes [this check for a buffer in undici](https://github.com/mcollina/undici/blob/master/lib/client.js#L946) fail.

Reproduction: https://github.com/timsuchanek/undici-buffer-repro

I'm already working on a fix :) I suggest adding a ` || Buffer.isBuffer(body)` in https://github.com/mcollina/undici/blob/master/lib/client.js#L946

**Comment by ronag** [comment]
I'm very curious what happens here. It shouldn't be possible for anyone to modify the `Request` object. Are they overriding `Buffer.from` or something?

**Comment by mcollina** [comment]
I would highly recommend to not use jest as __it provides different globals__ for each test, making all those check fail.
Anyway, a fix would be welcomed. Please also add a test for it.

**Comment by timsuchanek** [comment]
@mcollina I guess you recommend using `tap` instead? We have all our tests written in jest, but it has its limits.

We once hit a similar problem in Prisma Client, where we had an `instanceof Date` check. As a naive library author I thought that's sufficient - but there is some test environment, I think it was https://quokkajs.com/ that overrides the global Date, therefore the instanceof doesn't work anymore.
So we had to move to a `Object.prototype.toString` test instead.

**Comment by timsuchanek** [comment]
It's kinda awkward to add jest in there, but this is the only sane way I found to add the test https://github.com/mcollina/undici/pull/319

**Comment by SimenB** [comment]
Sorry about Jest causing issues 🙁 The issue to track (if anybody wants) in Jest for this is https://github.com/facebook/jest/issues/2549. I've tried multiple times to fix it without luck. I believe it can be solved if these two are ever solved:

- https://github.com/nodejs/node/issues/28823
- https://github.com/nodejs/node/issues/31852
