### ISSUE TITLE
path and pathname

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#322]
Some open thoughts on path and pathname:

- In our request api well call it `path`, but in `URL` it's called `pathname`. Should we change it? Support both? Leave it as is?

- We added in https://github.com/mcollina/undici/pull/313 so that we prepend the pathname from the URL passed to the client constructor. Some questions here:
  - If `Client.pathname`, should `Request.path.startsWith('/')` still be required?
  - Should `Client.pathname.endsWith('/')` be required or not? This is how the [current implementation](https://github.com/mcollina/undici/blob/master/lib/request.js#L51) works. Although a bit ugly.

**Comment by ronag** [comment]
@szmarczak @mcollina

**Comment by szmarczak** [comment]
I'd say let's go for `pathname`.

**Comment by szmarczak** [comment]
> If Client.pathname, should Request.path.startsWith('/') still be required?

IMO yes.

**Comment by ronag** [comment]
After some more though. I don't think we need to do anything here:

Reverted #313 (https://github.com/mcollina/undici/pull/326) to remove the issue.

Also in regard to `pathname` I was wrong. `pathname` only contains the pathname and not the search and hash. So it makes sense to call it `path` since it may contain search and hash. Similar to how `hostname` is just the hostname while `host` contains both the hostname and the port.
