### ISSUE TITLE
Support more buffer types

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#328]
There are quite a lot of different types of buffer objects in Node. Not quite sure what all of those are.

- `ArrayBuffer`
- `DataView`
- Different types of typed arrays
- etc...

We should probably support these?

**Comment by mcollina** [comment]
Only if needed?

**Comment by ronag** [comment]
> Only if needed?

How is that determined? You mean if someone requests it?

**Comment by mcollina** [comment]
Yes exactly.

**Comment by ronag** [comment]
Sounds reasonable.
