### ISSUE TITLE
review of servername handling

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#332]
I no longer quite remember the rules for servername handling.

I believe by default we always should use the `servername` passed in the `tls` option. However, if a request provides a host header which is a valid servername (i.e. not an IP), we should use that instead and reconnect if necessary.

This is what we do at the moment. Does that sound correct?

**Comment by szmarczak** [comment]
> we should use that instead and reconnect if necessary

Reconnect to what exactly? 🤔

**Comment by ronag** [comment]
> Reconnect to... what address? 🤔

Same address. Just a different `servername` option.

**Comment by ronag** [comment]
I think we are good here.
