### ISSUE TITLE
body with GET/HEAD

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#35]
What should happen if the user supplies a body with a GET/HEAD request? Should we throw an error?

**Comment by mcollina** [comment]
probably a good idea

**Comment by szmarczak** [comment]
Sometimes there's a badly written server and users are forced to send body with a GET method. I think it should be an option. See https://github.com/sindresorhus/got/issues/1074 https://github.com/sindresorhus/got/issues/966

**Comment by ronag** [comment]
Hm, that was quite a contentious. I guess we better allow it to avoid a repeat of that. Close? @mcollina?

**Comment by szmarczak** [comment]
I mean it can be disabled by default, but there should be an option to enable this.

**Comment by mcollina** [comment]
let’s allow it
