### ISSUE TITLE
var vs let?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#40]
I noticed this library is using var instead of let/const in some places. Is this intentional and how future code should be written as well?

**Comment by mcollina** [comment]
totally intentional for performance reason

**Comment by ronag** [comment]
> totally intentional for performance reason

Oh, I was not aware this was still a thing. Is it due to Node 10 support or is this also relevant for more recent V8 versions?

**Comment by szmarczak** [comment]
How does this `performance reason` look like under the hood?

**Comment by mcollina** [comment]
I had not time to do a check lately, but I see very little reason that are worth the switch. `const` is fine to use.
