### ISSUE TITLE
pause queue while piping

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#52]
I noticed the following comment https://github.com/mcollina/undici/blob/master/lib/client.js#L199.

I think if we don't fix this we have a serious bug where the next request can start writing to the socket interleaved with the current request body which will basically corrupt the whole client data stream. Or am I missing something?

**Comment by mcollina** [comment]
I think that comment is old/incorrect. The queue has a parallelism of 1, so it won't start processing a new entry before the callback is called.

**Comment by ronag** [comment]
Are you sure? Isn't the whole thing with queue concurrency (i.e. pipelining) that multiple tasks can be running concurrently?

**Comment by mcollina** [comment]
You are right, the problem exists.
