### ISSUE TITLE
pipelining should be relative number active requests?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#54]
Currently the logic is only relative to number of queued/inflight (?) requests, however a request might still be receiving the body before the next one is dispatched, e.g.  with pipelining 1 and a GET request with a large body, the next request would be dispatched before the body has been fully received.

Is this intentional or a bug?

**Comment by ronag** [comment]
e.g. `full` should probably be:

```js
const active = this[kQueue].length() + this[kInflight].length + (this[kLastBody] ? 1 : 0)
return active >= pipelining
```

**Comment by mcollina** [comment]
This is intentional. While the server is sending the previous body, it can start processing a new one.

**Comment by ronag** [comment]
@mcollina: There is one problem with this behavior though... currently there is no way to disable pipelining, i.e. I have a use case where I never want a request failing because the previous one failed while receiving the body.

Can we add support for that behavior with e.g. pipelining: 0?
