### ISSUE TITLE
Timeout behaviour unclear

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#58]
The way timeout is currently implement no request may take longer than 30 seconds. Shouldn't the timer be rescheduled every time something happens on the socket (i.e. read/write)?

With the current implementation a large payload over a slow connection will never succeed.

I would have expected timeout be relative to socket activity, not how long a request has been active, or more specifically how long it's been between scheduling of requests.

**Comment by ronag** [comment]
Another important reason for timeout to be relative to inactivity, most servers will kill a connection after e.g. 2 minutes of inactivity. Which can cause a race when a client sends a request just before this timeout, this causing the request to fail without anything really being wrong. 

Which is why, I at least, always ensure that persistent connections have an inactivity timeout well below the server to avoid these unnecessary request failures.

**Comment by ronag** [comment]
Any reason why we are not simply using socket timeout?

**Comment by ronag** [comment]
If it's because `retimer` has better performance than nodejs `Timer.refresh`, I guess we could monkey patch `Socket._unrefTimer`...

**Comment by mcollina** [comment]
retimer is a vestige of the past, we can totally drop it. It was needed on previous versions of Node.js where canceling timers was very slow.
