### ISSUE TITLE
Disabling pipelining

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#77]
As far as I can see, right now it is impossible to use this library in a way that only a single request is on the wire at the time.

Would it make sense to add `pipeling: 0` support which enforces that requests are first sent **and** received before the next one is sent.

**Comment by mcollina** [comment]
is pipelining: 1 not such a case? What would happen in that case?

**Comment by ronag** [comment]
> is pipelining: 1 not such a case? What would happen in that case?

We discussed this here https://github.com/mcollina/undici/issues/54.

Basically, it will send the next request while the response from the previous request is still being received.

**Comment by mcollina** [comment]
Aaah, I didn't connect the two together. I'm good either way with the pipelining 1 and pipelining 0 config. What do you think would be more intuitive?

**Comment by ronag** [comment]
I think 1 is more intuitive. I think we should change so that 1 is what I suggest which would make 2, what 1 is today. Makes sense?

**Comment by mcollina** [comment]
yes go ahead.
