### ISSUE TITLE
Check with spec

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#79]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html
https://tools.ietf.org/html/rfc7230

Do we follow the spec? Review.

**Comment by ronag** [comment]
@mcollina: Is there parts of the spec we know we don't implement and would like to?

e.g. socket upgrade, 100 continue etc...?

**Comment by mcollina** [comment]
I don’t think so.
I would not implement upgrade and 100 continue.

**Comment by ronag** [comment]
I'm leaving this open. I think we should at least document what do and what we do not support.
