### ISSUE TITLE
return null response when content-length 0?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#82]
We currently return `null` as response body when it's a `HEAD` request. 

We could also do the same when the response contains a `content-length: 0` header? 

Alternatively, always return a `Readable` for body to keep the response signature consistent.

Also, I'm a little unsure what happens with `HEAD` + `skipBody` if the server actually incorrectly sends a body?

**Comment by mcollina** [comment]
Maybe let’s return an empty readable.

**Comment by ronag** [comment]
> Maybe let’s return an empty readable.

What do you mean? We already do this for everything except `HEAD`. Do you mean we should empty readable for `HEAD` as well?

**Comment by mcollina** [comment]
I'm happy with whatever you prefer really. I thought returning null was ok, but if you prefer to return an empty readable is also ok.

**Comment by ronag** [comment]
let's leave it as is

**Comment by szmarczak** [comment]
I'd prefer an empty readable.

**Comment by szmarczak** [comment]
I mean just to be consistent so we don't need to write bunch of `if`s for edge cases.
