### ISSUE TITLE
request headers mutable?

### ISSUE THREAD

**Issue by ronag** [mcollina/undici#89]
Currently it is possible for the user to mutate the headers **after** calling `client.request(...)`. I'm not sure whether this is a good or bad thing?

As an alternative we could stringify the headers object to a `rawHeaders` buffer/string when creating the request object. That way, if the user modifies the headers object after `client.request(...)` it won't affect anything.

Thoughts?

**Comment by ronag** [comment]
@szmarczak how do you handle this in got?

**Comment by szmarczak** [comment]
We deep clone the options, including headers.

**Comment by ronag** [comment]
Not sure whether this library should take this into account. Not sure.

**Comment by szmarczak** [comment]
No need to implement deep cloning as a separate function. To save performance, I did the following:

```
options = {...options}
options.headers = {...options.headers}
```

**Comment by ronag** [comment]
I managed to do it with no perf impact https://github.com/nxtedition/undici/commit/ece6ee8456ca81fa54a37b09c529cb884a439a3a
